src/Entity/Comment.php
<?php
namespace App\Entity;

use App\Repository\CommentRepository;
use DateTimeImmutable;

class Comment
{

    /**
     * @var int|null
     */
    private ?int $id;

    /**
     * @var string|null
     */
    private ?string $content;

    /**
     * @var int|null
     */
    private ?int $user_id;

    /**
     * @var DateTimeImmutable|null
     */
    private ?DateTimeImmutable $created_at;

    /**
     * @var int|null
     */
    private ?int $parent_id;

    /**
     * @var int|null
     */
    private ?int $post_id;

    /**
     * @var bool|null
     */
    private ?bool $is_approved;

    /**
     * @var array|null
     */
    private ?array $children;

    /**
     * @param int|null $id
     * @param string|null $content
     * @param int|null $user_id
     * @param DateTimeImmutable|null $created_at
     * @param int|null $parent_id
     * @param int|null $post_id
     * @param bool|null $is_approved
     * @param array $children
     */
    public function __construct(
        int $id = null,
        string $content = null,
        int $user_id = null,
        DateTimeImmutable $created_at = null,
        int $parent_id = null,
        int $post_id = null,
        bool $is_approved = null,
        array $children = [],
    ) {
        $this->id = $id;
        $this->content = $content;
        $this->user_id = $user_id;
        $this->created_at = $created_at;
        $this->parent_id = $parent_id;
        $this->post_id = $post_id;
        $this->is_approved = $is_approved;
        $this->children = $children;
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return bool
     */
    public function getStatus(): bool
    {
        return $this->is_approved;
    }

    /**
     * @return string
     */
    public function getContent(): string
    {
        return $this->content;
    }

    /**
     * @param string $content
     * @return Comment
     */
    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return int
     */
    public function getAuthorId(): int
    {
        return $this->user_id;
    }

    /**
     * @param int $user_id
     * @return Comment
     */
    public function setAuthorId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * @return DateTimeImmutable
     */
    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->created_at;
    }

    /**
     * @param DateTimeImmutable $createdAt
     * @return Comment
     */
    public function setCreatedAt(DateTimeImmutable $createdAt): self
    {
        $this->created_at = $createdAt;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getParentId(): ?int
    {
        return $this->parent_id;
    }

    /**
     * @param int|null $parent_id
     * @return Comment
     */
    public function setParentId(?int $parent_id): self
    {
        $this->parent_id = $parent_id;

        return $this;
    }

    /**
     * @return int
     */
    public function getPostId(): int
    {
        return $this->post_id;
    }

    /**
     * @param int $post_id
     * @return Comment
     */
    public function setPostId(int $post_id): self
    {
        $this->post_id = $post_id;

        return $this;
    }

    /**
     * @return bool
     */
    public function isApproved(): bool
    {
        return $this->is_approved;
    }

    /**
     * @param bool $is_approved
     * @return Comment
     */
    public function setApproved(bool $is_approved): self
    {
        $this->is_approved = $is_approved;

        return $this;
    }

    /**
     * @return bool
     */
    public function hasChildren(): bool
    {
        return empty($this->children);
    }

    /**
     * @return array|null
     */
    public function getChildren(): ?array
    {
        return $this->children;
    }

    /**
     * @param array $data
     * @return Comment|null
     */
    public static function createFromDatabase(array $data): ?Comment
    {
        if (!$data) {

            return null;
        }
        $commentRepository = new CommentRepository();
        $createdAt = DateTimeImmutable::createFromFormat('Y-m-d H:i:s', $data['created_at']);

        return new self(
            $data['id'],
            $data['content'],
            $data['user_id'],
            $createdAt,
            $data['parent_id'],
            $data['post_id'],
            (bool)$data['is_approved'],
            $commentRepository->setChildren($data['id']),
        );
    }
}

src/Entity/Post.php
<?php

namespace App\Entity;

use DateTimeImmutable;

class Post
{

    /**
     * @var int|null
     */
    private ?int $id;

    /**
     * @var string|null
     */
    private ?string $title;

    /**
     * @var string|null
     */
    private ?string $slug;

    /**
     * @var string|null
     */
    private ?string $thumbnail;

    /**
     * @var string|null
     */
    private ?string $hat;

    /**
     * @var string|null
     */
    private ?string $content;

    /**
     * @var DateTimeImmutable|null
     */
    private ?DateTimeImmutable $created_at;

    /**
     * @var DateTimeImmutable|null
     */
    private ?DateTimeImmutable $updated_at;

    /**
     * @var bool|null
     */
    private ?Bool $is_active;

    /**
     * @var int|null
     */
    private ?int $user_id;

    public function __construct(
        int $id = null,
        string $title = null,
        string $slug = null,
        string $thumbnail = null,
        string $hat = null,
        string $content = null,
        DateTimeImmutable $created_at = null,
        DateTimeImmutable $updated_at = null,
        bool $is_active = null,
        int $user_id = null,
    )
    {
        $this->id = $id;
        $this->title = $title;
        $this->slug = $slug;
        $this->thumbnail = $thumbnail;
        $this->hat = $hat;
        $this->content = $content;
        $this->created_at = $created_at;
        $this->updated_at = $updated_at;
        $this->is_active = $is_active;
        $this->user_id = $user_id;
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param $title
     * @return Post
     */
    public function setTitle($title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * @param $slug
     * @return Post
     */
    public function setSlug($slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getThumbnail(): ?string
    {
        return $this->thumbnail;
    }

    /**
     * @param $thumbnail
     * @return Post
     */
    public function setThumbnail($thumbnail): self
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }

    /**
     * @return string
     */
    public function getHat(): string
    {
        return $this->hat;
    }

    /**
     * @param $hat
     * @return Post
     */
    public function setHat($hat): self
    {
        $this->hat = $hat;

        return $this;
    }

    /**
     * @return string
     */
    public function getContent(): string
    {
        return $this->content;
    }

    /**
     * @param $content
     * @return Post
     */
    public function setContent($content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return DateTimeImmutable
     */
    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->created_at;
    }

    /**
     * @param DateTimeImmutable $createdAt
     * @return Post
     */
    public function setCreatedAt(DateTimeImmutable $createdAt): self
    {
        $this->created_at = $createdAt;

        return $this;
    }

    /**
     * @return DateTimeImmutable
     */
    public function getUpdatedAt(): DateTimeImmutable
    {
        return $this->updated_at;
    }

    /**
     * @param $updatedAt
     * @return Post
     */
    public function setUpdatedAt($updatedAt): self
    {
        $this->updated_at = $updatedAt;

        return $this;
    }

    /**
     * @return int
     */
    public function getUserId(): int
    {
        return $this->user_id;
    }

    /**
     * @param $user_id
     * @return Post
     */
    public function setUserId($user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * @return bool
     */
    public function isActive(): bool
    {
        return $this->is_active;
    }

    /**
     * @param bool $is_active
     * @return Post
     */
    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    /**
     * @param array $data
     * @return Post|null
     */
    public static function createFromDatabase(array $data): ?Post
    {
        if (!$data) {

            return null;
        }
        $createdAt = DateTimeImmutable::createFromFormat('Y-m-d H:i:s', $data['created_at']);
        $updateAt = DateTimeImmutable::createFromFormat('Y-m-d H:i:s', $data['updated_at']);

        return new self(
            $data['id'],
            $data['title'],
            $data['slug'],
            $data['thumbnail'],
            $data['hat'],
            $data['content'],
            $createdAt,
            $updateAt,
            $data['is_active'],
            $data['user_id'],
        );
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Repository\CommentRepository;
use App\Repository\PostRepository;
use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\Response;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Error\SyntaxError;

/**
 *
 */
class PostController extends AbstractController
{
    private PostRepository $postRepository;
    private CommentRepository $commentRepository;

    public function __construct()
    {
        parent::__construct();
        $this->postRepository = new PostRepository();
        $this->commentRepository = new CommentRepository();
    }


    /**
     * Affiche la liste des articles (posts) du site.
     *
     * @return Response
     * @throws LoaderError
     * @throws RuntimeError
     * @throws SyntaxError
     */
    public function index(): Response
    {
        return $this->render('app/post/posts.html.twig', ['posts' => $this->postRepository->getPosts()]);
    }


    /**
     * Affiche un article (post) en fonction de son slug.
     *
     * @param string $slug
     * @return Response
     * @throws LoaderError
     * @throws RuntimeError
     * @throws SyntaxError
     */
    public function show(string $slug): Response
    {
        $successMessage = null;
        $errorMessage = null;
        $userRepository = new UserRepository();
        $commentRepository = new CommentRepository();

        $post = $this->postRepository->findBySlug($slug);
        if (!$post) {

            return new Response('Post not found', Response::HTTP_NOT_FOUND);
        }
        $users = $userRepository->getUsers();
        $comments = $this->commentRepository->getCommentsByPostId($post->getId());
        $content = $this->twig->render('app/post/show.html.twig', [
            'post' => $post,
            'comments' => $comments,
            'users' => $users,
            'message_success' => $successMessage,
            'message_error' => $errorMessage,
            'userRepository' => $userRepository,
            'commentRepository' => $commentRepository
        ]);

        return new Response($content);
    }
}

templates/app/post/index.html.twig
{% extends 'base.html.twig' %}

{% block page_title %}Articles{% endblock %}
{% block class_css %}articles{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Les articles :</h1>
        <h2>Les plus tendance :</h2>
        <div class="row">
            {% for post in posts %}
            <div class="col-md-4">
                <a href="/article/{{ post.slug }}">
                    <div class="card mb-4">
                        <img src="{{ post.thumbnail }}" alt="image de l'article" class="card-img-top">
                        <div class="card-body">
                            <h3 class="card-title">{{ post.title }}</h3>
                            <p class="card-text">{{ post.updatedAt|date('d/m/Y') }}</p>
                            <p class="card-text">{{ post.hat }}</p>
                        </div>
                    </div>
                </a>
            </div>
            {% if loop.index % 3 == 0 %}
        </div><div class="row">
            {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/app/post/posts.html.twig
{% extends 'base.html.twig' %}

{% block page_title %}Articles{% endblock %}
{% block class_css %}articles{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Les articles :</h1>
        <h2>Les plus tendance :</h2>
        <div class="row">
            {% for post in posts %}
            <div class="col-md-4">
                <a href="/article/{{ post.slug }}">
                    <div class="card mb-4">
                        <img src="{{ post.thumbnail }}" alt="image de l'article" class="card-img-top">
                        <div class="card-body">
                            <h3 class="card-title">{{ post.title }}</h3>
                            <p class="card-text">{{ post.updatedAt|date('d/m/Y') }}</p>
                            <div class="card-text">{{ post.hat|raw }}</div>
                        </div>
                    </div>
                </a>
            </div>
            {% if loop.index % 3 == 0 %}
        </div><div class="row">
            {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/app/post/show.html.twig
{% extends 'base.html.twig' %}

{% block page_title %}{{ post.title }}{% endblock %}
{% block class_css %}post{% endblock %}
{% block javascripts %}
    <script src="/assets/js/tinymce/langs/fr_FR.js"></script>
    <script src="/vendor/tinymce/tinymce/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="/assets/js/comments.js"></script>
{% endblock javascripts %}
{% block body %}

    <div class="post-image">
        <img src="{{ post.thumbnail }}" alt="{{ post.title }}" class="img-fluid">
        <div class="post-title-container">
            <h1 class="post-title">{{ post.title }}</h1>
        </div>
    </div>
    <div class="container">
        <div class="post-content">
            <h2>{{ post.hat|raw }}</h2>
            <p>Créé le {{ post.created_at|date('d/m/Y') }}</p>
            <p>Dernière modification le {{ post.updated_at|date('d/m/Y') }}</p>
            <div class="content">
                {{ post.content|raw }}
            </div>

            <div class="block">
                <div class="block-header">
                    <div class="title">
                        <h2>Commentaires</h2>
                        <div class="tag">{{ comments|length }}</div>
                    </div>
                </div>
                {% include 'app/post/_partials/_comment_form.html.twig' with {'post': post, 'commentId': null} %}
                {% if message_success %}
                    <div class="alert alert-success">{{ message_success }}</div>
                {% endif %}
                {% if message_error %}
                    <div class="alert alert-danger">{{ message_error }}</div>
                {% endif %}
                {% if comments|length > 0 %}
                    {% for comment in comments %}
                        {% if comment.parentId == null %}
                            <div class="comment">
                                <div class="user-banner">
                                    <div class="user">
                                        <div class="avatar">
                                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
                                                 alt="Avatar" class="img-fluid my-5" style="width: 80px;"/>
                                        </div>
                                        <h5>{{ users[comment.authorId].username }}</h5>
                                    </div>
                                    <button class="btn dropdown"><i class="ri-more-line"></i></button>
                                </div>
                                <div class="content">
                                    {{ comment.content|raw }}
                                </div>
                                <div class="footer">
                                    <span data-comment-id="{{ comment.id }}" class="reply_btn">Répondre</span>
                                    <div class="divider"></div>
                                    <span class="is-mute">{% include 'app/post/_partials/_comment_date.html.twig' with {'comment': comment} %}</span>
                                </div>
                            </div>
                            {% if comment.hasChildren() %}
                                {% include 'app/post/_partials/_comment_form.html.twig' with {'post': post, 'commentId': comment.id} %}
                            {% endif %}
                            {% for childComment in comment.children %}
                                {% set childComment = comments[childComment] %}
                                {% set authorChildComment = users[childComment.authorId] %}
                                <div class="reply comment">
                                    <div class="user-banner">
                                        <div class="user">
                                            <div class="avatar">
                                                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
                                                     alt="Avatar" class="img-fluid my-5" style="width: 80px;"/>
                                            </div>
                                            <h5>{{ authorChildComment.username }}</h5>
                                        </div>
                                        <button class="btn dropdown"><i class="ri-more-line"></i></button>
                                    </div>
                                    <div class="content">
                                        {{ childComment.content|raw }}
                                    </div>
                                    <div class="footer">
                                        <span class="is-mute">{% include 'app/post/_partials/_comment_date.html.twig' with {'comment': childComment} %}</span>
                                    </div>
                                </div>
                                {% if loop.last %}
                                    {% include 'app/post/_partials/_comment_form.html.twig' with {'post': post, 'commentId': comment.id} %}
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}